// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $0 from "./routes/_404.tsx";
import * as $1 from "./routes/_app.tsx";
import * as $2 from "./routes/_middleware.ts";
import * as $3 from "./routes/all/index.tsx";
import * as $4 from "./routes/api/joke.ts";
import * as $5 from "./routes/bookmarks/index.tsx";
import * as $6 from "./routes/greet/[name].tsx";
import * as $7 from "./routes/index.tsx";
import * as $8 from "./routes/review/index.tsx";
import * as $9 from "./routes/signin/index.tsx";
import * as $10 from "./routes/signout.ts";
import * as $11 from "./routes/words/[word].tsx";
import * as $$0 from "./islands/AddDefinition.tsx";
import * as $$1 from "./islands/Counter.tsx";
import * as $$2 from "./islands/LoadWords.tsx";
import * as $$3 from "./islands/NavbarSearch.tsx";
import * as $$4 from "./islands/WordDefinition.tsx";
import * as $$5 from "./islands/auth/SignInForm.tsx";
import * as $$6 from "./islands/bookmarks/BookmarkedWords.tsx";

const manifest = {
  routes: {
    "./routes/_404.tsx": $0,
    "./routes/_app.tsx": $1,
    "./routes/_middleware.ts": $2,
    "./routes/all/index.tsx": $3,
    "./routes/api/joke.ts": $4,
    "./routes/bookmarks/index.tsx": $5,
    "./routes/greet/[name].tsx": $6,
    "./routes/index.tsx": $7,
    "./routes/review/index.tsx": $8,
    "./routes/signin/index.tsx": $9,
    "./routes/signout.ts": $10,
    "./routes/words/[word].tsx": $11,
  },
  islands: {
    "./islands/AddDefinition.tsx": $$0,
    "./islands/Counter.tsx": $$1,
    "./islands/LoadWords.tsx": $$2,
    "./islands/NavbarSearch.tsx": $$3,
    "./islands/WordDefinition.tsx": $$4,
    "./islands/auth/SignInForm.tsx": $$5,
    "./islands/bookmarks/BookmarkedWords.tsx": $$6,
  },
  baseUrl: import.meta.url,
};

export default manifest;
